#!/bin/bash
#Apache Directory Name
NITROSH_APACHE_DIR=''
NITROSH_BI_INT_HOST='77.246.39.193'
NITROSH_SITES_DIR='/Library/WebServer/Documents'
NITROSH_DRUPAL_DIR=''
NITROSH_MYSQL_USER='root'
NITROSH_MYSQL_PASSWORD='root'

